# Generated by Django 6.0.7 on 2026-08-29 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schoolclass_position'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task_per_school',
        ),
        migrations.AddField(
            model_name='task',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='Renseigné uniquement pour le ménage de la salle de cette classe. Géré automatiquement avec la classe.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_task', to='core.schoolclass'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('school_class__isnull', True)), fields=('school', 'name'), name='unique_task_per_school'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('school_class',), name='one_cleaning_task_per_class'),
        ),
    ]
