# Generated by Django 6.0.7 on 2026-08-29 18:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cleaning_task_per_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='task',
            field=models.ForeignKey(on_delete=core.models.protect_unless_class_task, related_name='assignments', to='core.task'),
        ),
    ]
